feat(deployment): deploy sequencer in system test workflow (#6730)

diff --git a/.github/workflows/consolidated_system_test.yaml b/.github/workflows/consolidated_system_test.yaml
--- a/.github/workflows/consolidated_system_test.yaml
+++ b/.github/workflows/consolidated_system_test.yaml
@@ -18,6 +18,7 @@ on:
 env:
   job_link: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
   deployment_config_path: ${{ github.workspace }}/config/sequencer/testing/deployment_configs/deployment_test_consolidated.json
+  namespace: sequencer-consolidated-system-test-run-${{ github.run_number }}-attempt-${{ github.run_attempt }}
 
 permissions:
   contents: read
@@ -33,6 +34,18 @@ jobs:
     steps:
       - name: Checkout repository
         uses: actions/checkout@v4
+
+      - name: Create k3d cluster (Local k8s)
+        uses: AbsaOSS/k3d-action@v2
+        with:
+          # Assumption: only one PR can run per machine at a time.
+          cluster-name: "consolidated-system-test"
+          args: >-
+            --verbose
+            --agents 1
+            --no-lb
+            --wait
+            --timeout 120s
 
       # Install rust components.
       - uses: ./.github/actions/bootstrap
@@ -53,7 +66,6 @@ jobs:
       - name: Setup pipenv
         run: python3 -m pip install pipenv
 
-      # TODO(Nadin): add requirements.txt file.
       - name: Install dependencies with pipenv
         run: pipenv install kubernetes
 
@@ -82,6 +94,42 @@ jobs:
         run: |
           python ./scripts/system_tests/config_secrets_injector.py --deployment_config_path ${{ env.deployment_config_path }} --secrets_json '${{ vars.SEQUENCER_CONFIG_JSON }}'
 
+      - name: Generate k8s manifests
+        working-directory: deployments/sequencer
+        run: |
+          pipenv install
+          cdk8s import
+          echo "Generating Kubernetes manifests using deployment config at: ${{ env.deployment_config_path }}:"
+          cat "${{ env.deployment_config_path }}"
+          cdk8s synth --app "pipenv run python main.py --namespace ${{ env.namespace }} --deployment-config-file ${{ env.deployment_config_path }}"
 
+      - name: Deploy Sequencer
+        working-directory: deployments/sequencer
+        run: |
+          echo "Deploying Sequencer..."
+          kubectl create namespace ${{ env.namespace }}
+          kubectl apply -R -f ./dist/
 
+      - name: Set default namespace
+        run: kubectl config set-context --current --namespace ${{ env.namespace }}
 
+      - name: Get container logs
+        if: always()
+        run: |
+          echo "📥 Getting pod logs and descriptions from namespace: $namespace"
+
+          # List all pods in the namespace
+          kubectl get pods -n "$namespace"
+
+          # For each pod, get logs and description
+          for pod in $(kubectl get pods -n "$namespace" -o jsonpath='{.items[*].metadata.name}'); do
+            echo "---------------------------------------------"
+            echo "Logs for pod: $pod"
+            kubectl logs -n "$namespace" "$pod" || echo "⚠️ Failed to get logs for $pod"
+
+            echo ""
+            echo "Description for pod: $pod"
+            kubectl describe pod -n "$namespace" "$pod" || echo "⚠️ Failed to describe pod $pod"
+            echo "---------------------------------------------"
+            echo ""
+          done
