deployment: add simulator to the system test - POC

diff --git a/.github/workflows/consolidated_system_test.yaml b/.github/workflows/consolidated_system_test.yaml
--- a/.github/workflows/consolidated_system_test.yaml
+++ b/.github/workflows/consolidated_system_test.yaml
@@ -230,7 +230,7 @@ jobs:
           kubectl wait --namespace ${{ env.namespace }} --for=condition=Ready -l app=anvil pod --timeout 60s
           echo "🚀 Anvil deployed successfully."
 
-          echo "🔍 Extracting Anvil addresses from logs."
+          echo "🔍 Extracting Anvil addresses from logs"
 
           ANVIL_POD=$(kubectl get pods -n "${{ env.namespace }}" -l app=anvil -o jsonpath="{.items[0].metadata.name}")
           ANVIL_LOGS=$(kubectl logs -n "${{ env.namespace }}" "$ANVIL_POD")
@@ -319,6 +319,48 @@ jobs:
       - name: Copy state and restart pod
         run: pipenv run python ./scripts/system_tests/copy_state_and_restart.py --deployment_config_path ${{ env.deployment_config_path }} --data-dir "./output/data/node_0/executable_0"
 
+      - name: Port-forward Anvil pod to localhost:8545
+        run: |
+          echo "🔌 Setting up port-forward to Anvil..."
+
+          ANVIL_POD=$(kubectl get pods -n anvil -l app=anvil -o jsonpath="{.items[0].metadata.name}")
+          echo "🌐 Found Anvil pod: $ANVIL_POD"
+
+          # Start port-forwarding in background and keep it running
+          kubectl port-forward -n anvil "$ANVIL_POD" 8545:8545 &
+          echo "⏳ Waiting a few seconds to ensure port-forward is established..."
+          sleep 2
+
+      # - name: Port-forward dummy recorder pod to localhost:8081
+      #   run: |
+      #     echo "🔌 Setting up port-forward to dummy recorder..."
+
+      #     RECORDER_POD=$(kubectl get pods -n dummy-recorder -l app=dummy-recorder -o jsonpath="{.items[0].metadata.name}")
+      #     echo "🌐 Found dummy-recorder pod: $RECORDER_POD"
+
+      #     # Start port-forwarding in background and keep it running
+      #     kubectl port-forward -n dummy-recorder "$RECORDER_POD" 8085:8080 &
+      #     echo "⏳ Waiting a few seconds to ensure port-forward is established..."
+      #     sleep 2
+
+      # - name: Port-forward dummy-eth-to-strk pod to localhost:8081
+      #   run: |
+      #     echo "🔌 Setting up port-forward to dummy-eth-to-strk..."
+
+      #     ETHTOSTRK_POD=$(kubectl get pods -n dummy-eth-to-strk -l app=dummy-eth2strk-oracle -o jsonpath="{.items[0].metadata.name}")
+      #     echo "🌐 Found dummy-eth-to-strk pod: $ETHTOSTRK_POD"
+
+      #     # Start port-forwarding in background and keep it running
+      #     kubectl port-forward -n dummy-eth-to-strk "$ETHTOSTRK_POD" 8086:8080 &
+      #     echo "⏳ Waiting a few seconds to ensure port-forward is established..."
+      #     kubectl get svc -n dummy-recorder
+      #     kubectl get pods -n dummy-recorder -l app=dummy-recorder
+
+      #     sleep 2
+
+      - name: Send transactions test
+        run: pipenv run python ./scripts/system_tests/sequencer_simulator.py --deployment_config_path ${{ env.deployment_config_path }} --config_dir "${{ env.config_dir }}" --node_type "consolidated" --sender_address "${{ env.SENDER_ADDRESS }}" --receiver_address "${{ env.RECEIVER_ADDRESS }}"
+
       - name: Get container logs
         if: always()
         run: |
@@ -326,6 +368,8 @@ jobs:
 
           # List all pods in the namespace
           kubectl get pods -n "$namespace"
+
+          kubectl describe pvc sequencer-node-data -n "$namespace"
 
           # For each pod, get logs and description
           for pod in $(kubectl get pods -n "$namespace" -o jsonpath='{.items[*].metadata.name}'); do
@@ -339,3 +383,9 @@ jobs:
             echo "---------------------------------------------"
             echo ""
           done
+
+      - name: Delete k3d cluster
+        if: always()
+        run: |
+          echo "🧹 Cleaning up k3d cluster..."
+          k3d cluster delete ${{ env.cluster_name }} || echo "⚠️ Failed to delete cluster (maybe it didn't exist)"
