chore(ci): add simple docker test on sequencer docker publish workflow

diff --git a/.github/workflows/sequencer_docker-publish.yml b/.github/workflows/sequencer_docker-publish.yml
--- a/.github/workflows/sequencer_docker-publish.yml
+++ b/.github/workflows/sequencer_docker-publish.yml
@@ -89,4 +89,27 @@ jobs:
           push: ${{ github.event_name != 'pull_request' }}
           tags: ${{ steps.meta.outputs.tags }}
           labels: ${{ steps.meta.outputs.labels }}
+          load: true # Loads the build result to docker images. Required for "Run docker test" step to work.
           no-cache: true
+
+      - name: Run basic docker test
+        env:
+          TIMEOUT_DURATION: "30s"
+          SEQUENCER_CONFIG_PATH: "./config/sequencer/presets/system_test_presets/single_node_config.json"
+        run: |
+          # converts steps.meta.outputs.tags array to bash array.
+          tags="${{ steps.meta.outputs.tags }}"
+          tags_array=($tags)
+          tag=${tags_array[0]}
+
+          timeout ${{ env.TIMEOUT_DURATION }} docker run -e 'RUST_LOG=debug' -e 'RUST_BACKTRACE=full' "$tag" --config_file ${{ env.SEQUENCER_CONFIG_PATH }} || exit_code="$?"
+
+          # Return code 124 from `timeout` process means timeout reached, which considered success for this test.
+          if (( $exit_code == 124 )); then
+            echo "Docker ran successfully for $TIMEOUT_DURATION!"
+            exit 0
+          # Any other return codes could be application or docker failure.
+          else
+            echo "Docker failed or exited prematurely with exit code $exit_code."
+            exit 1
+          fi
